// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaeukvtrnooltxkdxqtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZXVrdnRybm9vbHR4a2R4cXRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1Mzg2MTgsImV4cCI6MjA5MDExNDYxOH0.vLlELkYDoYg3Y12eGefRriEmdcpSNB5n3hrM82X-E_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});